<link rel="stylesheet" href="http://192.168.1.20:8888/arcgis_js_api/library/3.8/3.8compact/js/dojo/dijit/themes/tundra/tundra.css"> 
<link rel="stylesheet" href="http://192.168.1.20:8888/arcgis_js_api/library/3.8/3.8compact/js/dojo/dijit/themes/claro/claro.css">
<link rel="stylesheet" href="http://192.168.1.20:8888/arcgis_js_api/library/3.8/3.8compact/js/esri/css/esri.css">
<script type="text/javascript">djConfig = { parseOnLoad:true }</script>
<script type="text/javascript" src="http://192.168.1.20:8888/arcgis_js_api/library/3.8/3.8compact/init.js"></script>
<script type="text/javascript" src="gis/gis.js" charset="UTF-8"></script>
<script type="text/javascript" src="gis/showMove.js" charset="UTF-8"></script>
<script type="text/javascript" src="gis/drawSection.js" charset="UTF-8"></script>
<script type="text/javascript" src="gis/gisLayer.js" charset="UTF-8"></script>
<script type="text/javascript" src="gis/drawSection2.js" charset="UTF-8"></script>
