package com.hatc.common.hibernate.pojo;

import java.util.Date;

/**
 * TbLocal generated by MyEclipse - Hibernate Tools
 */

public class TbLocal implements java.io.Serializable {

	// Fields

	private static final long serialVersionUID = 1452903095087931150L;

	private String siteId;

	private String verOnline;

	private String verOffline;

	private Date startts;

	private Long busiMonth;

	// Constructors

	/** default constructor */
	public TbLocal() {
	}

	/** minimal constructor */
	public TbLocal(String siteId) {
		this.siteId = siteId;
	}

	/** full constructor */
	public TbLocal(String siteId, String verOnline, String verOffline,
			Date startts, Long busiMonth) {
		this.siteId = siteId;
		this.verOnline = verOnline;
		this.verOffline = verOffline;
		this.startts = startts;
		this.busiMonth = busiMonth;
	}

	// Property accessors

	public String getSiteId() {
		return this.siteId;
	}

	public void setSiteId(String siteId) {
		this.siteId = siteId;
	}

	public String getVerOnline() {
		return this.verOnline;
	}

	public void setVerOnline(String verOnline) {
		this.verOnline = verOnline;
	}

	public String getVerOffline() {
		return this.verOffline;
	}

	public void setVerOffline(String verOffline) {
		this.verOffline = verOffline;
	}

	public Date getStartts() {
		return this.startts;
	}

	public void setStartts(Date startts) {
		this.startts = startts;
	}

	public Long getBusiMonth() {
		return this.busiMonth;
	}

	public void setBusiMonth(Long busiMonth) {
		this.busiMonth = busiMonth;
	}

}