package com.hatc.common.hibernate.pojo;

/**
 * TbOnline generated by MyEclipse - Hibernate Tools
 */

public class TbOnline implements java.io.Serializable {

	// Fields

	private static final long serialVersionUID = 1855194318469122492L;

	private TbOnlineId id;

	private String roleId;

	private String loginTime;

	private String loginLocation;

	private String loginMode;

	// Constructors

	/** default constructor */
	public TbOnline() {
	}

	/** minimal constructor */
	public TbOnline(TbOnlineId id) {
		this.id = id;
	}

	/** full constructor */
	public TbOnline(TbOnlineId id, String roleId, String loginTime,
			String loginLocation, String loginMode) {
		this.id = id;
		this.roleId = roleId;
		this.loginTime = loginTime;
		this.loginLocation = loginLocation;
		this.loginMode = loginMode;
	}

	// Property accessors

	public TbOnlineId getId() {
		return this.id;
	}

	public void setId(TbOnlineId id) {
		this.id = id;
	}

	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public String getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(String loginTime) {
		this.loginTime = loginTime;
	}

	public String getLoginLocation() {
		return this.loginLocation;
	}

	public void setLoginLocation(String loginLocation) {
		this.loginLocation = loginLocation;
	}

	public String getLoginMode() {
		return this.loginMode;
	}

	public void setLoginMode(String loginMode) {
		this.loginMode = loginMode;
	}

}