package com.hatc.common.hibernate.pojo;

/**
 * TbOnlineId generated by MyEclipse - Hibernate Tools
 */

public class TbOnlineId implements java.io.Serializable {

	// Fields

	private static final long serialVersionUID = 2090057956934182145L;

	private String userId;

	private String sessionId;

	// Constructors

	/** default constructor */
	public TbOnlineId() {
	}

	/** full constructor */
	public TbOnlineId(String userId, String sessionId) {
		this.userId = userId;
		this.sessionId = sessionId;
	}

	// Property accessors

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbOnlineId))
			return false;
		TbOnlineId castOther = (TbOnlineId) other;

		return ((this.getUserId() == castOther.getUserId()) || (this
				.getUserId() != null
				&& castOther.getUserId() != null && this.getUserId().equals(
				castOther.getUserId())))
				&& ((this.getSessionId() == castOther.getSessionId()) || (this
						.getSessionId() != null
						&& castOther.getSessionId() != null && this
						.getSessionId().equals(castOther.getSessionId())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result
				+ (getSessionId() == null ? 0 : this.getSessionId().hashCode());
		return result;
	}

}