package com.hatc.common.hibernate.pojo;

/**
 * TbSite generated by MyEclipse Persistence Tools
 */

public class TbSite implements java.io.Serializable {
    
    // Fields
    private static final long serialVersionUID = -3001061412147861722L;
    
    private String siteId;
    
    private String siteName;
    
    private String airdromeName;
    
    private Long sysFlag;
    
    private Long exportFlag;
    
    private String longLaTitude;
    
    private String deptId;
    
    private Long utc;
    
    // Constructors
    
    /** default constructor */
    public TbSite() {
    }
    
    /** minimal constructor */
    public TbSite(String siteId) {
        this.siteId = siteId;
    }
    
    /** full constructor */
    public TbSite(String siteId, String siteName, String airdromeName, Long sysFlag, Long exportFlag,
            String longLaTitude, String deptId, Long utc) {
        this.siteId = siteId;
        this.siteName = siteName;
        this.airdromeName = airdromeName;
        this.sysFlag = sysFlag;
        this.exportFlag = exportFlag;
        this.longLaTitude = longLaTitude;
        this.deptId = deptId;
        this.utc = utc;
    }
    
    // Property accessors
    
    public String getSiteId() {
        return this.siteId;
    }
    
    public void setSiteId(String siteId) {
        this.siteId = siteId;
    }
    
    public String getSiteName() {
        return this.siteName;
    }
    
    public void setSiteName(String siteName) {
        this.siteName = siteName;
    }
    
    public String getAirdromeName() {
        return this.airdromeName;
    }
    
    public void setAirdromeName(String airdromeName) {
        this.airdromeName = airdromeName;
    }
    
    public Long getSysFlag() {
        return this.sysFlag;
    }
    
    public void setSysFlag(Long sysFlag) {
        this.sysFlag = sysFlag;
    }
    
    public Long getExportFlag() {
        return this.exportFlag;
    }
    
    public void setExportFlag(Long exportFlag) {
        this.exportFlag = exportFlag;
    }
    
    public String getLongLaTitude() {
        return this.longLaTitude;
    }
    
    public void setLongLaTitude(String longLaTitude) {
        this.longLaTitude = longLaTitude;
    }
    
    public String getDeptId() {
        return this.deptId;
    }
    
    public void setDeptId(String deptId) {
        this.deptId = deptId;
    }
    
    public Long getUtc() {
        return this.utc;
    }
    
    public void setUtc(Long utc) {
        this.utc = utc;
    }
    
}