<script src="http://maps.google.com/maps/api/js?sensor=true&libraries=geometry"></script>
<script type="text/javascript" src="http://www.google.com/jsapi" charset="utf-8"></script>
<script type="text/javascript" src="./earthview/js/math3d.js" charset="utf-8"></script>
<script type="text/javascript" src="./earthview/js/plane.js" charset="utf-8"></script>
<script type="text/javascript" src="./earthview/js/global.js" charset="utf-8"></script>
<script type="text/javascript" src="./earthview/js/jquery.flot.min.js" charset="utf-8"></script>
<script type="text/javascript" src="./earthview/js/jquery.flot.crosshair.min.js" charset="utf-8"></script>
<script type="text/javascript" src="./earthview/js/jquery.flot.symbol.min.js" charset="utf-8"></script>

<script type="text/javascript">

var basePath ="<%=basePath %>";
